# Generated by Django 5.0.6 on 2024-06-12 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='product_images',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Shopping.product'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_images',
        ),
        migrations.AlterField(
            model_name='productvideo',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='Shopping.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_images',
            field=models.ManyToManyField(blank=True, related_name='videos', to='Shopping.productimage'),
        ),
    ]
