# Generated by Django 5.0.6 on 2024-06-12 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping', '0002_productimage_product_images_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='product_images',
            new_name='product',
        ),
    ]
