# Generated by Django 5.0.6 on 2024-06-12 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping', '0004_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='explain',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
